Repository UM-USElab/gradecraft-development, pull requests merged in 2018-02, with the labels that each got.

#3797 2746 Add email to send to instructors on course creation
  app/controllers/users_controller.rb
  app/mailers/user_mailer.rb
  app/services/sends_resource_email.rb
  app/services/sends_resource_email/mark_user_as_received_resources.rb
  app/services/sends_resource_email/send_email.rb
  app/views/user_mailer/app_resources_email.html.haml
  app/views/user_mailer/app_resources_email.text.haml
  app/views/user_mailer/umich_resources_email.html.haml
  app/views/user_mailer/umich_resources_email.text.haml
  config/environments/development.rb
  db/migrate/20180126133414_add_viewed_resources_field_to_user.rb
  db/schema.rb
  spec/mailers/user_mailer/user_mailer_spec.rb
  test/mailers/previews/user_mailer_preview.rb
Labels: feedback provided

#3870 Don't allow course publishing if unpaid and app
  app/controllers/courses_controller.rb
  app/models/abilities/course_ability.rb
  app/proctors/course_proctor.rb
  app/views/layouts/_course_publication.haml
  spec/controllers/courses_controller_spec.rb
Labels: bug

#3818 Nightly score recalculations
  Gemfile
  Gemfile.lock
  Rakefile
  app/background_jobs/queue_score_recalculator_job.rb
  config/initializers/resque.rb
  config/resque_schedule.yml
  config/routes.rb
  lib/admin_constraint.rb
  lib/tasks/scores.rake
  spec/background_jobs/queue_score_recalculator_job_spec.rb
Labels: in progress

#3862 Gradecraft Profiling
  Gemfile
  Gemfile.lock
  app/controllers/assignments_controller.rb
  app/controllers/badges_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/info_controller.rb
  app/controllers/teams_controller.rb
  app/models/concerns/analytics/user_analytics.rb
  app/models/timeline.rb
  app/models/user.rb
  app/presenters/info/dashboard_course_planner_presenter.rb
  app/views/assignments/_index_staff.haml
  app/views/info/dashboard/modules/_dashboard_instructor_grading_scheme.haml
  config/environments/development.rb
  db/migrate/20180215211948_add_missing_indexes.rb
  db/schema.rb
  spec/controllers/api/learning_objectives/levels_controller_spec.rb
Labels: performance

#3483 3093 attendance assignment type
  app/assets/javascripts/angular/directives/assignments/media_uploader.coffee
  app/assets/javascripts/angular/directives/attendance/days_of_week.coffee
  app/assets/javascripts/angular/directives/attendance/event_attribute_card.coffee
  app/assets/javascripts/angular/directives/attendance/event_attributes.coffee
  app/assets/javascripts/angular/directives/attendance/form_entry.coffee
  app/assets/javascripts/angular/directives/attendance/mass_edit.coffee
  app/assets/javascripts/angular/directives/attendance/setup_form.coffee
  app/assets/javascripts/angular/directives/common/date_picker_input.coffee
  app/assets/javascripts/angular/services/AttendanceService.coffee
  app/assets/javascripts/angular/templates/assignments/media_uploader.html.haml
  app/assets/javascripts/angular/templates/attendance/_days_of_week.html.haml
  app/assets/javascripts/angular/templates/attendance/_event_attribute_card.html.haml
  app/assets/javascripts/angular/templates/attendance/_event_attributes.html.haml
  app/assets/javascripts/angular/templates/attendance/_form_entry.html.haml
  app/assets/javascripts/angular/templates/attendance/mass_edit.html.haml
  app/assets/javascripts/angular/templates/attendance/setup_form.html.haml
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/pages/_attendance.sass
  app/controllers/api/attendance_controller.rb
  app/controllers/assignment_types_controller.rb
  app/controllers/assignments_controller.rb
  app/controllers/attendance_controller.rb
  app/models/assignment.rb
  app/models/assignment_type.rb
  app/models/breadcrumb_trail.rb
  app/models/course.rb
  app/views/api/attendance/_assignment.json.jbuilder
  app/views/api/attendance/index.json.jbuilder
  app/views/api/attendance/show.json.jbuilder
  app/views/assignment_types/_form.html.haml
  app/views/assignments/_index_observer.haml
  app/views/attendance/index.html.haml
  app/views/attendance/mass_edit.html.haml
  app/views/attendance/new.html.haml
  app/views/attendance/setup.html.haml
  app/views/layouts/navigation/_observer_profile_tabs.haml
  app/views/layouts/navigation/_staff_subnav_links.haml
  app/views/layouts/navigation/_student_profile_tabs.haml
  config/locales/views/titles/en.yml
  config/routes.rb
  db/migrate/20170629151215_add_attendance_to_assignment_types.rb
  db/schema.rb
  spec/controllers/api/attendance_controller_spec.rb
  spec/controllers/attendance_controller_spec.rb
  spec/factories/assignment_type_factory.rb
Labels: feature request, feedback provided, needs review

#3882 Fix attachments being hidden, media not loading
  app/assets/javascripts/angular/templates/assignments/media_uploader.html.haml
  app/views/api/attendance/_assignment.json.jbuilder
Labels: bug

#3887 Make Rubrics Order Again
  app/assets/javascripts/angular/directives/rubrics/design.coffee
Labels: bug

#3725 3686 Authenticate through Google
  app/assets/images/Google.svg
  app/assets/stylesheets/components/_buttons_and_icons.sass
  app/assets/stylesheets/pages/_login.sass
  app/controllers/authorizations_controller.rb
  app/controllers/google_calendars/assignments_controller.rb
  app/controllers/google_calendars/events_controller.rb
  app/controllers/google_controller.rb
  app/helpers/google_calendars_helper.rb
  app/views/pages/auth_failure.html.haml
  app/views/user_sessions/_form.html.haml
  app/views/user_sessions/_gradecraft.html.haml
  app/views/users/activate_set_password.html.haml
  config/initializers/omniauth.rb
  config/routes.rb
  spec/controllers/google_calendars/assignments_controller_spec.rb
  spec/controllers/google_calendars/events_controller_spec.rb
Labels: feature request, in progress
