Repository UM-USElab/gradecraft-development, pull requests merged in 2018-08, with the labels that each got.

#4036 Clean up routes, fix grade release
  app/assets/javascripts/angular/directives/assignments/show/group/table.coffee
  app/assets/javascripts/angular/directives/assignments/show/individual/table.coffee
  app/assets/javascripts/angular/directives/grading_status/grades.coffee
  app/assets/javascripts/angular/services/GradeReleaseService.coffee
  app/controllers/api/assignments/grades_controller.rb
  config/routes.rb
  spec/controllers/api/assignments/grades_controller_spec.rb
Labels: bug

#4021 4010 delete memberships
  app/controllers/course_memberships_controller.rb
  app/models/breadcrumb_trail.rb
  app/views/course_memberships/index.html.haml
  app/views/layouts/navigation/_staff_subnav_links.haml
  config/routes.rb
  spec/controllers/course_membership_controller_spec.rb
  spec/controllers/course_memberships_controller_spec.rb
Labels: needs review

#4052 Fix Undefined Variable Bug
  app/views/submissions/_assignment_guidelines.haml
Labels: bug

#4064 Dependent destroy submission exports
  app/models/assignment.rb
Labels: bug

#4048 Remove Hard Failure From Learning Objectives
  app/controllers/api/learning_objectives/objectives_controller.rb
  app/models/learning_objective.rb
  spec/models/learning_objective_spec.rb
Labels: in progress

#4054 3930 learning objective show
  app/assets/javascripts/angular/directives/assignments/descriptor_icons.coffee
  app/assets/javascripts/angular/directives/common/sortable_header.coffee
  app/assets/javascripts/angular/directives/learning_objectives/objectives/design.coffee
  app/assets/javascripts/angular/directives/learning_objectives/objectives/show.coffee
  app/assets/javascripts/angular/services/LearningObjectivesService.coffee
  app/assets/javascripts/angular/services/SortableService.coffee
  app/assets/javascripts/angular/services/SubmissionService.coffee
  app/assets/javascripts/angular/templates/assignments/descriptor_icons.html.haml
  app/assets/javascripts/angular/templates/learning_objectives/grade_overview.html.haml
  app/assets/javascripts/angular/templates/learning_objectives/objectives/show.html.haml
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/components/_progress_bars.sass
  app/assets/stylesheets/pages/_learning_objectives.sass
  app/assets/stylesheets/pages/_rubrics.sass
  app/controllers/api/learning_objectives/outcomes_controller.rb
  app/controllers/api/submissions_controller.rb
  app/models/learning_objective.rb
  app/models/submission.rb
  app/services/cancels_course_membership/destroys_submissions.rb
  app/views/api/assignments/_assignment.json.jbuilder
  app/views/api/assignments/_assignment_unlocks.json.jbuilder
  app/views/api/courses/students/index.json.jbuilder
  app/views/api/learning_objectives/objectives/show.json.jbuilder
  app/views/api/learning_objectives/outcomes/index.json.jbuilder
  app/views/api/submissions/index.json.jbuilder
  app/views/assignments/index_student/components/_assignment_icons.haml
  app/views/learning_objectives/components/_progress_bar.html.haml
  app/views/learning_objectives/links/index.html.haml
  config/routes.rb
Labels: needs review
