Repository UM-USElab/gradecraft-development, pull requests merged in 2018-05, with the labels that each got.

#3965 Group assignments refactor
  app/assets/javascripts/angular/directives/assignments/groups/grades/mass_edit_form.coffee
  app/assets/javascripts/angular/directives/assignments/show/group/_student_table.coffee
  app/assets/javascripts/angular/directives/assignments/show/group/table.coffee
  app/assets/javascripts/angular/directives/assignments/show/group/table_body.coffee
  app/assets/javascripts/angular/directives/assignments/show/individual/table.coffee
  app/assets/javascripts/angular/helpers/serviceHelpers.js.coffee
  app/assets/javascripts/angular/services/AssignmentGradesService.coffee
  app/assets/javascripts/angular/services/GradeReleaseService.coffee
  app/assets/javascripts/angular/templates/assignments/groups/grades/mass_edit_form.html.haml
  app/assets/javascripts/angular/templates/assignments/show/group/_student_table.html.haml
  app/assets/javascripts/angular/templates/assignments/show/group/table.html.haml
  app/assets/javascripts/angular/templates/assignments/show/group/table_body.html.haml
  app/controllers/api/assignments/groups/grades_controller.rb
  app/controllers/assignments/grades_controller.rb
  app/views/api/assignments/groups/grades/index.json.jbuilder
  app/views/api/assignments/groups/grades/mass_edit.json.jbuilder
  app/views/assignments/_show_staff.haml
  app/views/assignments/group/_group_show.haml
  app/views/assignments/group/_table_body.html.haml
  app/views/assignments/group/_table_head.html.haml
  config/routes.rb
  spec/controllers/api/assignments/groups/grades_controller_spec.rb
  spec/controllers/assignments/grades_controller_spec.rb
Labels: feature improvement

#3968 3967 Google Batch Bug
  app/presenters/info/dashboard_course_events_presenter.rb
  app/proctors/assignment_proctor.rb
  app/views/info/dashboard/modules/_dashboard_course_events.haml
  spec/proctors/assignment_proctor_spec.rb
Labels: feedback provided

#3982 Refactor grading status
  app/assets/javascripts/angular/directives/assignments/show/group/table.coffee
  app/assets/javascripts/angular/directives/assignments/show/individual/table.coffee
  app/assets/javascripts/angular/directives/common/collapse_toggler.coffee
  app/assets/javascripts/angular/directives/common/sortable_search_input.coffee
  app/assets/javascripts/angular/directives/grading_status/grades.coffee
  app/assets/javascripts/angular/directives/grading_status/submissions.coffee
  app/assets/javascripts/angular/services/GradeReleaseService.coffee
  app/assets/javascripts/angular/services/GradingStatusService.coffee
  app/assets/javascripts/angular/templates/common/sortable_search_input.html.haml
  app/assets/javascripts/angular/templates/grading_status/grades.html.haml
  app/assets/javascripts/angular/templates/grading_status/submissions.html.haml
  app/assets/stylesheets/components/_buttons_and_icons.sass
  app/assets/stylesheets/pages/_grades.sass
  app/controllers/api/assignments/grades_controller.rb
  app/controllers/api/grading_status/grades_controller.rb
  app/controllers/api/grading_status/submissions_controller.rb
  app/controllers/info_controller.rb
  app/views/api/grading_status/grades/index.json.jbuilder
  app/views/api/grading_status/submissions/index.json.jbuilder
  app/views/info/_grades_table.haml
  app/views/info/_submissions_table.haml
  app/views/info/grading_status.html.haml
  config/routes.rb
  spec/controllers/api/assignments/grades_controller_spec.rb
  spec/controllers/api/grading_status/grades_controller_spec.rb
  spec/controllers/api/grading_status/submissions_controller_spec.rb
  spec/factories/submission_factory.rb
Labels: needs review

#3971 Student index improvements
  app/assets/javascripts/angular/directives/assignments/show/individual/table_body.coffee
  app/assets/javascripts/angular/directives/courses/students/_table_filter.coffee
  app/assets/javascripts/angular/directives/courses/students/index.coffee
  app/assets/javascripts/angular/services/CourseMembershipService.coffee
  app/assets/javascripts/angular/services/CourseService.coffee
  app/assets/javascripts/angular/services/StudentService.coffee
  app/assets/javascripts/angular/services/TeamService.coffee
  app/assets/javascripts/angular/templates/assignments/show/individual/table_body.html.haml
  app/assets/javascripts/angular/templates/common/team_selector.html.haml
  app/assets/javascripts/angular/templates/courses/students/_table_filter.html.haml
  app/assets/javascripts/angular/templates/courses/students/index.html.haml
  app/assets/javascripts/application.js
  app/assets/javascripts/dynatable_student_index.js
  app/assets/stylesheets/base/_typography.sass
  app/assets/stylesheets/layout/_forms.sass
  app/controllers/api/courses/students_controller.rb
  app/controllers/api/courses_controller.rb
  app/controllers/course_memberships_controller.rb
  app/controllers/students_controller.rb
  app/controllers/users_controller.rb
  app/presenters/students/index_presenter.rb
  app/views/api/courses/show.json.jbuilder
  app/views/api/courses/students/index.json.jbuilder
  app/views/students/_students_table.haml
  app/views/students/_table_filter.html.haml
  app/views/students/index.html.haml
  config/routes.rb
  spec/controllers/api/courses/students_controller_spec.rb
  spec/presenters/students/index_presenter_spec.rb
Labels: needs review
