Repository UM-USElab/gradecraft-development, pull requests merged in 2018-03, with the labels that each got.

#3890 Change condition for which model callback happens
  app/models/assignment_type.rb
  spec/models/assignment_type_spec.rb
Labels: bug

#3893 Reset multiplier-related fields if unused
  app/assets/javascripts/angular/templates/predictor/main.html.haml
  app/models/course.rb
  spec/factories/course_factory.rb
  spec/models/course_spec.rb
  spec/views/api/assignment_types/index_spec.rb
Labels: bug

#3903 Assignment copy fix
  app/models/assignment.rb
Labels: bug

#3901 Hide assignment types on the student index until assignmsn visible
  app/models/assignment_type.rb
  app/views/assignments/index_student/_assignments.haml
Labels: bug, feature improvement

#3897 Add copy validation
  app/controllers/assignments_controller.rb
  app/controllers/courses_controller.rb
  app/models/assignment.rb
  app/models/concerns/copyable.rb
  app/models/copy_validator.rb
  app/models/course.rb
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/courses_controller_spec.rb
  spec/models/assignment_spec.rb
  spec/models/copy_validator_spec.rb
  spec/models/course_spec.rb
Labels: needs review

#3905 Fix assignment visibility bug
  app/models/assignment_type.rb
  spec/models/assignment_type_spec.rb
Labels: bug

#3914 Pass around group_id param, fix issues with partial
  app/controllers/submissions_controller.rb
  app/views/info/_submissions_table.haml
  app/views/submissions/show.html.haml
Labels: bug

#3934 Add recaptcha to trial creation form
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/views/users/new_external.html.haml
  spec/controllers/users_controller_spec.rb
Labels: needs review

#3918 Fix visibility bug on outcome progress
  app/models/learning_objective.rb
  app/models/learning_objective_cumulative_outcome.rb
  spec/factories/learning_objective_observed_outcome_factory.rb
  spec/models/learning_objective_observed_outcome_spec.rb
  spec/models/learning_objective_spec.rb
Labels: bug
